### ISSUE TITLE
CICD: skip build for doc-only changes

### ISSUE THREAD

**Issue by dthaler** [dthaler/rst2rfcxml#20]
When build.yml has:
```
on:
  pull_request:
    paths-ignore:
      - '**.md'
```

Then the workflow is skipped for doc-only changes.  However, then the workflow cannot be marked as required for code changes.  Instead the workflow should be required, and only specific jobs should be skipped for doc-only changes.

https://github.com/marketplace/actions/skip-duplicate-actions#example-1-skip-entire-jobs looks like it should work.
